### ISSUE TITLE
404 when trying to install prerequisites 

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/prometheus-dcos#2]
I can't seem to find the prerequisite repositories to use this project. 

https://github.com/mesosphere/universe/tree/prometheus
https://github.com/mesosphere/prometheus-dcos/blob/master/prometheus/mesos_exporter
https://github.com/mesosphere/prometheus-dcos/blob/master/github.com/prometheus/node_exporter

Are all giving 404s

**Comment by discordianfish** [comment]
Oh sorry about that. Should be fixed now!
